"""
Requirement Verifier Agent Profile

This profile defines the Team 1 Verifier that validates task packets generated
by RequirementSupervisor to ensure quality and consistency.
"""

import os
import sys
from typing import List, Dict, Any, Optional
from dataclasses import dataclass
from enum import Enum

# Add project root to path
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(os.path.dirname(CURRENT_DIR))
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)


class ToolCategory(str, Enum):
    VALIDATION = "验证"
    ANALYSIS = "分析"


class KnowledgeDomain(str, Enum):
    VALIDATION = "验证"
    QUALITY_ASSURANCE = "质量保证"


@dataclass
class AgentRole:
    name: str
    description: str
    responsibilities: List[str]
    expertise: List[str]


@dataclass
class AgentTool:
    name: str
    function_signature: str
    description: str
    parameters: List[Dict[str, str]]
    returns: str
    category: ToolCategory
    usage_example: Optional[str] = None
    dependencies: List[str] = None

    def __post_init__(self):
        if self.dependencies is None:
            self.dependencies = []


@dataclass
class AgentKnowledge:
    domain: KnowledgeDomain
    concepts: List[str]
    rules: List[str]


@dataclass
class AgentProfile:
    agent_id: str
    description: str = ""
    role: AgentRole = None
    tools: List[AgentTool] = None
    knowledge: List[AgentKnowledge] = None
    constraints: List[str] = None
    best_practices: List[str] = None
    resources: List[str] = None
    run_methods: List[str] = None
    command: Optional[str] = None
    guide_book: Optional[str] = None

    def __post_init__(self):
        if self.tools is None:
            self.tools = []
        if self.knowledge is None:
            self.knowledge = []
        if self.constraints is None:
            self.constraints = []
        if self.best_practices is None:
            self.best_practices = []
        if self.resources is None:
            self.resources = []
        if self.run_methods is None:
            self.run_methods = []


REQUIREMENT_VERIFIER_ROLE = AgentRole(
    name="Requirement Verifier",
    description=(
        "Team 1 verifier responsible for validating task packets generated by "
        "RequirementSupervisor. Checks completeness, consistency, and quality of "
        "instructions and constraints for Team 2 and Team 3."
    ),
    responsibilities=[
        "Validate task packet structure and completeness",
        "Check instruction clarity and actionability",
        "Verify constraint extraction correctness",
        "Detect conflicts between Team 2 and Team 3 requirements",
        "Ensure modality addresses are valid",
        "Validate requirement parsing quality",
        "Check team selection appropriateness",
        "Report validation issues with specific recommendations",
    ],
    expertise=[
        "Task packet validation",
        "Instruction quality assessment",
        "Constraint consistency checking",
        "Cross-team requirement validation",
        "Quality assurance for requirement analysis",
    ],
)


REQUIREMENT_VERIFIER_TOOLS = [
    AgentTool(
        name="validate_task_packet_structure",
        function_signature="validate_task_packet_structure(packet: Dict[str, Any]) -> Dict[str, Any]",
        description="Validate that task packet has all required fields and correct structure",
        parameters=[
            {"name": "packet", "type": "Dict[str, Any]", "description": "Task packet to validate"},
        ],
        returns="Validation result with passed flag and missing fields list",
        category=ToolCategory.VALIDATION,
    ),
    AgentTool(
        name="validate_instruction_quality",
        function_signature="validate_instruction_quality(instruction: str, team_name: str) -> Dict[str, Any]",
        description="Check if instruction is clear, specific, and actionable",
        parameters=[
            {"name": "instruction", "type": "str", "description": "Task instruction text"},
            {"name": "team_name", "type": "str", "description": "Target team name"},
        ],
        returns="Quality assessment with score and improvement suggestions",
        category=ToolCategory.VALIDATION,
    ),
    AgentTool(
        name="validate_constraints",
        function_signature="validate_constraints(constraints: List[str], profile: Dict) -> Dict[str, Any]",
        description="Verify constraints are correctly extracted from profile",
        parameters=[
            {"name": "constraints", "type": "List[str]", "description": "Extracted constraints"},
            {"name": "profile", "type": "Dict", "description": "Source agent profile"},
        ],
        returns="Validation result with missing or incorrect constraints",
        category=ToolCategory.VALIDATION,
    ),
    AgentTool(
        name="validate_modality_consistency",
        function_signature="validate_modality_consistency(modalities: List[str], addresses: Dict) -> Dict[str, Any]",
        description="Check consistency between detected modalities and provided addresses",
        parameters=[
            {"name": "modalities", "type": "List[str]", "description": "Detected modality list"},
            {"name": "addresses", "type": "Dict", "description": "Modality address mappings"},
        ],
        returns="Validation result with inconsistencies",
        category=ToolCategory.VALIDATION,
    ),
    AgentTool(
        name="validate_team_selection",
        function_signature="validate_team_selection(needed_teams: Dict, requirement: Dict) -> Dict[str, Any]",
        description="Verify team selection is appropriate for the requirement",
        parameters=[
            {"name": "needed_teams", "type": "Dict", "description": "Selected teams"},
            {"name": "requirement", "type": "Dict", "description": "Parsed requirement"},
        ],
        returns="Validation result with appropriateness assessment",
        category=ToolCategory.VALIDATION,
    ),
]


REQUIREMENT_VERIFIER_KNOWLEDGE = [
    AgentKnowledge(
        domain=KnowledgeDomain.VALIDATION,
        concepts=[
            "Task packet structure requirements",
            "Instruction quality criteria",
            "Constraint extraction rules",
            "Modality consistency checks",
        ],
        rules=[
            "Task packet must have: team_name, instruction, constraints, modalities, modality_addresses",
            "Instruction must be specific and actionable, not generic",
            "Constraints must come from profile, not invented",
            "Modalities list must match non-empty addresses",
            "Team 2 required if any modality present",
            "Team 3 required if music generation mentioned",
            "Instruction length should be 50-500 characters",
            "At least 3 constraints should be extracted per team",
        ],
    ),
    AgentKnowledge(
        domain=KnowledgeDomain.QUALITY_ASSURANCE,
        concepts=[
            "Quality metrics for task packets",
            "Common validation failure patterns",
            "Improvement recommendations",
        ],
        rules=[
            "Empty or placeholder instructions fail validation",
            "Generic instructions like 'process data' fail validation",
            "Missing required fields fail validation",
            "Inconsistent modality detection fails validation",
            "Validation should provide actionable feedback",
        ],
    ),
]


REQUIREMENT_VERIFIER_PROFILE = AgentProfile(
    agent_id="requirement_verifier_v1",
    description=(
        "Team 1 Requirement Verifier validating task packets generated by RequirementSupervisor. "
        "Checks structure, instruction quality, constraint correctness, and cross-team consistency."
    ),
    role=REQUIREMENT_VERIFIER_ROLE,
    tools=REQUIREMENT_VERIFIER_TOOLS,
    knowledge=REQUIREMENT_VERIFIER_KNOWLEDGE,
    constraints=[
        "Must validate all required fields in task packets",
        "Cannot pass validation if critical fields are missing",
        "Must provide specific, actionable feedback for failures",
        "Cannot modify task packets, only validate them",
    ],
    best_practices=[
        "Check structure before content quality",
        "Validate both Team 2 and Team 3 packets",
        "Provide specific examples in failure messages",
        "Prioritize critical issues over minor ones",
        "Suggest concrete improvements, not just flag problems",
    ],
    resources=[
        "Team1/AgentProfile/requirement_supervisor_profile.py",
        "Team2/AgentProfile/scene_understanding_supervisor_profile.py",
        "Team3/AgentProfile/music_generation_supervisor_profile.py",
    ],
    run_methods=[
        "Receive requirement_analysis_result from RequirementSupervisor",
        "Validate Team 2 task packet structure",
        "Validate Team 3 task packet structure",
        "Check instruction quality for both teams",
        "Verify constraint extraction correctness",
        "Validate modality consistency",
        "Check team selection appropriateness",
        "Generate validation report with pass/fail and issues",
        "Provide improvement recommendations if validation fails",
    ],
    command="verify_requirement_analysis",
    guide_book=(
        "Validation Workflow:\n"
        "1. Structure Validation - Check all required fields present\n"
        "2. Instruction Quality - Assess clarity and actionability\n"
        "3. Constraint Validation - Verify extraction from profiles\n"
        "4. Modality Consistency - Check modalities match addresses\n"
        "5. Team Selection - Verify appropriate teams selected\n"
        "6. Cross-Team Consistency - Check no conflicts between packets\n"
        "7. Generate Report - Pass/fail with specific issues and recommendations\n"
    ),
)


if __name__ == "__main__":
    print("Requirement Verifier Agent Profile")
    print("=" * 80)
    print(f"Agent ID: {REQUIREMENT_VERIFIER_PROFILE.agent_id}")
    print(f"Role: {REQUIREMENT_VERIFIER_PROFILE.role.name}")
    print(f"Tools: {len(REQUIREMENT_VERIFIER_PROFILE.tools)}")
    print(f"Knowledge domains: {len(REQUIREMENT_VERIFIER_PROFILE.knowledge)}")
