"""
Requirement Verifier Agent

Team 1 verifier that validates task packets generated by RequirementSupervisor.
Checks structure, instruction quality, constraint correctness, and consistency.
"""

import os
import sys
import json
from typing import Dict, Any, List, Optional

# Add project root to path
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(os.path.dirname(CURRENT_DIR))
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

try:
    from Team1.AgentProfile.requirement_verifier_profile import REQUIREMENT_VERIFIER_PROFILE
except ImportError:
    from AgentProfile.requirement_verifier_profile import REQUIREMENT_VERIFIER_PROFILE


class RequirementVerifier:
    """
    Team 1 Requirement Verifier

    Validates task packets generated by RequirementSupervisor to ensure:
    - Structure completeness
    - Instruction quality
    - Constraint correctness
    - Modality consistency
    - Team selection appropriateness
    """

    def __init__(self):
        """Initialize RequirementVerifier"""
        self.profile = REQUIREMENT_VERIFIER_PROFILE
        self.required_packet_fields = [
            "team_name",
            "instruction",
            "constraints",
            "modalities",
            "modality_addresses",
            "user_requirement",
            "parsed_requirement",
        ]

    def verify(self, requirement_analysis_result: Dict[str, Any]) -> Dict[str, Any]:
        """
        Verify requirement analysis result

        Args:
            requirement_analysis_result: Output from RequirementSupervisor

        Returns:
            Verification result with passed flag, issues, and recommendations
        """
        print("\n[Verifier] Starting validation...")

        issues = []
        warnings = []

        # Validate structure
        structure_issues = self._validate_structure(requirement_analysis_result)
        issues.extend(structure_issues)

        # Validate Team 2 packet
        if requirement_analysis_result.get("team2_task_packet"):
            team2_issues = self._validate_task_packet(
                requirement_analysis_result["team2_task_packet"],
                "Team2"
            )
            issues.extend(team2_issues)
        else:
            issues.append("Missing Team 2 task packet")

        # Validate Team 3 packet
        if requirement_analysis_result.get("team3_task_packet"):
            team3_issues = self._validate_task_packet(
                requirement_analysis_result["team3_task_packet"],
                "Team3"
            )
            issues.extend(team3_issues)
        else:
            warnings.append("Missing Team 3 task packet (may be intentional)")

        # Validate modality consistency
        modality_issues = self._validate_modality_consistency(requirement_analysis_result)
        issues.extend(modality_issues)

        # Validate team selection
        team_issues = self._validate_team_selection(requirement_analysis_result)
        warnings.extend(team_issues)

        passed = len(issues) == 0

        result = {
            "passed": passed,
            "issues": issues,
            "warnings": warnings,
            "recommendations": self._generate_recommendations(issues, warnings),
        }

        print(f"[Verifier] Validation {'PASSED' if passed else 'FAILED'}")
        print(f"[Verifier] Issues: {len(issues)}, Warnings: {len(warnings)}")

        return result

    def _validate_structure(self, result: Dict[str, Any]) -> List[str]:
        """Validate overall structure"""
        issues = []

        required_fields = [
            "user_requirement",
            "parsed_requirement",
            "available_modalities",
            "needed_teams",
        ]

        for field in required_fields:
            if field not in result or result[field] is None:
                issues.append(f"Missing required field: {field}")

        return issues

    def _validate_task_packet(self, packet: Dict[str, Any], team_name: str) -> List[str]:
        """Validate a single task packet"""
        issues = []

        # Check required fields
        for field in self.required_packet_fields:
            if field not in packet or packet[field] is None:
                issues.append(f"{team_name}: Missing required field '{field}'")

        # Validate instruction quality
        instruction = packet.get("instruction", "")
        if len(instruction) < 50:
            issues.append(f"{team_name}: Instruction too short ({len(instruction)} chars, min 50)")
        elif len(instruction) > 1000:
            issues.append(f"{team_name}: Instruction too long ({len(instruction)} chars, max 1000)")

        if not instruction or instruction.strip() == "":
            issues.append(f"{team_name}: Empty instruction")

        # Check for generic/placeholder instructions
        generic_patterns = ["process", "handle", "deal with", "work on", "..."]
        if any(pattern in instruction.lower() for pattern in generic_patterns):
            if len(instruction) < 100:  # Short + generic = likely placeholder
                issues.append(f"{team_name}: Instruction appears generic or placeholder")

        # Validate constraints
        constraints = packet.get("constraints", [])
        if not constraints:
            issues.append(f"{team_name}: No constraints provided")
        elif len(constraints) < 3:
            issues.append(f"{team_name}: Too few constraints ({len(constraints)}, recommended min 3)")

        # Check constraint quality
        for i, constraint in enumerate(constraints):
            if not constraint or len(constraint) < 10:
                issues.append(f"{team_name}: Constraint {i+1} is too short or empty")

        return issues

    def _validate_modality_consistency(self, result: Dict[str, Any]) -> List[str]:
        """Validate modality consistency"""
        issues = []

        available_modalities = result.get("available_modalities", [])

        # Check Team 2 packet modalities
        team2_packet = result.get("team2_task_packet")
        if team2_packet:
            packet_modalities = team2_packet.get("modalities", [])
            if set(packet_modalities) != set(available_modalities):
                issues.append(
                    f"Team2: Modality mismatch - available: {available_modalities}, "
                    f"in packet: {packet_modalities}"
                )

            # Check addresses match modalities
            addresses = team2_packet.get("modality_addresses", {})
            for modality in available_modalities:
                address_key = f"{modality}_address"
                if address_key not in addresses:
                    issues.append(f"Team2: Missing address for modality '{modality}'")
                elif not addresses[address_key]:
                    issues.append(f"Team2: Empty address list for modality '{modality}'")

        return issues

    def _validate_team_selection(self, result: Dict[str, Any]) -> List[str]:
        """Validate team selection appropriateness"""
        warnings = []

        available_modalities = result.get("available_modalities", [])
        needed_teams = result.get("needed_teams", {})
        parsed_req = result.get("parsed_requirement", {})

        # Team 2 should be selected if any modality present
        if available_modalities and "Team2" not in needed_teams:
            warnings.append("Team2 not selected despite available modalities")

        # Team 3 should be selected if music generation mentioned
        if parsed_req:
            objectives = parsed_req.get("objectives", [])
            if isinstance(objectives, list):
                objectives_text = " ".join(str(obj).lower() for obj in objectives)
            else:
                objectives_text = str(objectives).lower()

            music_keywords = ["music", "song", "audio generation", "prompt"]
            has_music_objective = any(kw in objectives_text for kw in music_keywords)

            if has_music_objective and "Team3" not in needed_teams:
                warnings.append("Team3 not selected despite music generation objective")

        return warnings

    def _generate_recommendations(self, issues: List[str], warnings: List[str]) -> List[str]:
        """Generate actionable recommendations"""
        recommendations = []

        if any("instruction" in issue.lower() for issue in issues):
            recommendations.append(
                "Improve instruction quality: Be specific about what needs to be done, "
                "include context, and avoid generic phrases"
            )

        if any("constraint" in issue.lower() for issue in issues):
            recommendations.append(
                "Extract more constraints from agent profiles: Check profile.constraints "
                "and profile.knowledge.rules for additional constraints"
            )

        if any("modality" in issue.lower() for issue in issues):
            recommendations.append(
                "Fix modality consistency: Ensure modalities list matches non-empty addresses"
            )

        if any("missing" in issue.lower() for issue in issues):
            recommendations.append(
                "Complete all required fields: Review task packet structure requirements"
            )

        return recommendations


def main():
    """Test RequirementVerifier"""
    print("=" * 80)
    print("Testing RequirementVerifier")
    print("=" * 80)

    verifier = RequirementVerifier()

    # Test case 1: Valid result
    print("\n[Test 1] Valid requirement analysis result")
    valid_result = {
        "user_requirement": "Test requirement",
        "parsed_requirement": {"objectives": ["music generation"]},
        "available_modalities": ["text"],
        "needed_teams": {"Team2": ["scene_understanding"], "Team3": ["music_generation"]},
        "team2_task_packet": {
            "team_name": "Team2",
            "instruction": "Analyze the provided text input to extract scene information including mood, style, and temporal structure for music generation.",
            "constraints": [
                "Must output 9-field scene representation",
                "Must preserve temporal ordering",
                "Must validate scene consistency",
            ],
            "modalities": ["text"],
            "modality_addresses": {
                "text_address": ["test.txt"],
                "audio_address": [],
                "photo_address": [],
                "video_address": [],
            },
            "user_requirement": "Test requirement",
            "parsed_requirement": {"objectives": ["music generation"]},
        },
        "team3_task_packet": {
            "team_name": "Team3",
            "instruction": "Generate music prompts based on scene analysis, including lyrics, descriptions, and audio type specifications.",
            "constraints": [
                "Must generate blueprint first",
                "Must ensure language consistency",
                "Must validate emotional alignment",
            ],
            "modalities": ["text"],
            "modality_addresses": {
                "text_address": ["test.txt"],
                "audio_address": [],
                "photo_address": [],
                "video_address": [],
            },
            "user_requirement": "Test requirement",
            "parsed_requirement": {"objectives": ["music generation"]},
        },
    }

    result = verifier.verify(valid_result)
    print(f"\nPassed: {result['passed']}")
    print(f"Issues: {result['issues']}")
    print(f"Warnings: {result['warnings']}")

    # Test case 2: Invalid result (missing fields)
    print("\n" + "=" * 80)
    print("[Test 2] Invalid result - missing fields")
    invalid_result = {
        "user_requirement": "Test",
        "available_modalities": ["text"],
        "team2_task_packet": {
            "team_name": "Team2",
            "instruction": "Short",  # Too short
            "constraints": [],  # Empty
        },
    }

    result = verifier.verify(invalid_result)
    print(f"\nPassed: {result['passed']}")
    print(f"Issues ({len(result['issues'])}):")
    for issue in result['issues']:
        print(f"  - {issue}")
    print(f"Recommendations:")
    for rec in result['recommendations']:
        print(f"  - {rec}")

    print("\n" + "=" * 80)
    print("RequirementVerifier tests completed")
    print("=" * 80)


if __name__ == "__main__":
    main()
