"""
Reflection Memory Module

Stores and manages agent reflection history, based on the Reflexion paper's
episodic memory mechanism. Uses a sliding window strategy to limit the maximum
number of stored entries and prevent excessive context length.

Reflexion core concepts:
- Short-term memory: current trajectory history
- Long-term memory: verbal experience feedback generated by the reflection model
- Amplify sparse feedback signals into actionable improvement suggestions through self-reflection

Storage location: reflection_memory.json in the same directory as the agent
"""

import os
import json
import uuid
from datetime import datetime
from typing import List, Dict, Any, Optional
from dataclasses import dataclass, field, asdict
from pathlib import Path


@dataclass
class ReflectionEntry:
    """Single reflection record"""
    id: str                           # Unique identifier
    timestamp: str                    # Timestamp
    task_type: str                   # Task type (text/audio/photo/video/multi/pop)
    task_description: str            # Task description
    observation: str                  # Observation result
    reflection: str                   # Reflection content
    improvement: str                 # Improvement suggestions
    quality: str                      # Reflection quality assessment (high/medium/low)
    iterations: int                   # Number of iterations

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ReflectionEntry":
        return cls(**data)


class ReflectionMemory:
    """
    Reflection Memory Manager

    Core functionality:
    1. Add new reflection - add_reflection()
    2. Get recent N entries - get_recent_reflections()
    3. Get all memories - get_all()
    4. Clear memory - clear()
    5. Save/Load - save()/load()

    Uses a sliding window strategy with default max storage of 3 entries
    (per Reflexion paper recommendation).
    """

    DEFAULT_MAX_SIZE = 3
    DEFAULT_STORAGE_FILE = "reflection_memory.json"

    def __init__(
        self,
        agent_type: str = "default",
        max_size: int = DEFAULT_MAX_SIZE,
        storage_dir: Optional[str] = None
    ):
        """
        Initialize the reflection memory module.

        Args:
            agent_type: Agent type identifier, used to distinguish different agents' memories
            max_size: Maximum number of stored entries, default 3 (per Reflexion paper)
            storage_dir: Storage directory, defaults to same level as agent file
        """
        self.agent_type = agent_type
        self.max_size = max_size
        self.storage_dir = storage_dir

        # Internal storage
        self._reflections: List[ReflectionEntry] = []

        # Statistics
        self._total_reflections = 0
        self._last_updated: Optional[str] = None

    def add_reflection(
        self,
        task_description: str,
        observation: str,
        reflection: str,
        improvement: str = "",
        quality: str = "medium",
        iterations: int = 1
    ) -> str:
        """
        Add a new reflection record.

        Args:
            task_description: Task description
            observation: Observed results
            reflection: Reflection content
            improvement: Improvement suggestions
            quality: Reflection quality
            iterations: Number of iterations used

        Returns:
            ID of the new record
        """
        entry = ReflectionEntry(
            id=str(uuid.uuid4())[:8],
            timestamp=datetime.now().isoformat(),
            task_type=self.agent_type,
            task_description=task_description,
            observation=observation,
            reflection=reflection,
            improvement=improvement,
            quality=quality,
            iterations=iterations
        )

        # Add to the beginning of the list (newest first)
        self._reflections.insert(0, entry)

        # Sliding window: remove oldest if exceeding max size
        if len(self._reflections) > self.max_size:
            self._reflections = self._reflections[:self.max_size]

        # Update statistics
        self._total_reflections += 1
        self._last_updated = entry.timestamp

        # Auto-save
        self.save()

        return entry.id

    def get_recent_reflections(self, n: int = 3) -> List[Dict[str, Any]]:
        """
        Get the most recent N reflections.

        Args:
            n: Number of entries to retrieve, default 3

        Returns:
            List of reflection records, each containing reflection content and improvement suggestions
        """
        recent = self._reflections[:min(n, len(self._reflections))]
        return [
            {
                "reflection": entry.reflection,
                "improvement": entry.improvement,
                "quality": entry.quality,
                "timestamp": entry.timestamp
            }
            for entry in recent
        ]

    def get_all(self) -> List[Dict[str, Any]]:
        """
        Get all reflection records.

        Returns:
            List of all reflection records
        """
        return [entry.to_dict() for entry in self._reflections]

    def get_summary(self) -> str:
        """
        Get memory summary for embedding in prompts.

        Returns:
            Formatted memory summary string
        """
        if not self._reflections:
            return "No historical reflection records."

        summary_parts = []
        for i, entry in enumerate(self._reflections[:self.max_size], 1):
            summary_parts.append(
                f"Reflection {i}:\n"
                f"  Task: {entry.task_description[:50]}...\n"
                f"  Reflection: {entry.reflection[:100]}...\n"
                f"  Improvement: {entry.improvement[:100]}..."
            )

        return "\n\n".join(summary_parts)

    def clear(self) -> None:
        """Clear all reflection memories."""
        self._reflections.clear()
        self._last_updated = datetime.now().isoformat()
        self.save()

    def get_stats(self) -> Dict[str, Any]:
        """
        Get memory statistics.

        Returns:
            Dictionary containing statistics
        """
        quality_counts = {}
        for entry in self._reflections:
            quality_counts[entry.quality] = quality_counts.get(entry.quality, 0) + 1

        return {
            "agent_type": self.agent_type,
            "current_size": len(self._reflections),
            "max_size": self.max_size,
            "total_reflections": self._total_reflections,
            "last_updated": self._last_updated,
            "quality_distribution": quality_counts
        }

    def save(self, filepath: Optional[str] = None) -> None:
        """
        Save memory to file.

        Args:
            filepath: Custom file path; defaults to file in storage directory
        """
        if filepath is None and self.storage_dir:
            filepath = os.path.join(self.storage_dir, self.DEFAULT_STORAGE_FILE)
        elif filepath is None:
            filepath = self.DEFAULT_STORAGE_FILE

        # Ensure directory exists
        if filepath:
            os.makedirs(os.path.dirname(filepath) or ".", exist_ok=True)

        data = {
            "agent_type": self.agent_type,
            "max_size": self.max_size,
            "total_reflections": self._total_reflections,
            "last_updated": self._last_updated,
            "reflections": [entry.to_dict() for entry in self._reflections]
        }

        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

    def load(self, filepath: Optional[str] = None) -> None:
        """
        Load memory from file.

        Args:
            filepath: Custom file path; defaults to file in storage directory
        """
        if filepath is None and self.storage_dir:
            filepath = os.path.join(self.storage_dir, self.DEFAULT_STORAGE_FILE)
        elif filepath is None:
            filepath = self.DEFAULT_STORAGE_FILE

        if not os.path.exists(filepath):
            return  # File doesn't exist, use empty memory

        try:
            with open(filepath, "r", encoding="utf-8") as f:
                data = json.load(f)

            self.agent_type = data.get("agent_type", self.agent_type)
            self.max_size = data.get("max_size", self.max_size)
            self._total_reflections = data.get("total_reflections", 0)
            self._last_updated = data.get("last_updated")

            self._reflections = [
                ReflectionEntry.from_dict(entry)
                for entry in data.get("reflections", [])
            ]
        except (json.JSONDecodeError, KeyError) as e:
            print(f"Warning: Failed to load reflection memory: {e}")
            self._reflections = []

    @classmethod
    def for_agent(cls, agent_type: str, storage_dir: Optional[str] = None) -> "ReflectionMemory":
        """
        Convenience factory method: create memory module for a specific agent.

        Args:
            agent_type: Agent type (text/audio/photo/video/multi/pop/ningbgm)
            storage_dir: Storage directory

        Returns:
            Configured ReflectionMemory instance
        """
        return cls(
            agent_type=agent_type,
            max_size=cls.DEFAULT_MAX_SIZE,
            storage_dir=storage_dir
        )


# Global singletons (use as needed)
_global_memories: Dict[str, ReflectionMemory] = {}


def get_reflection_memory(agent_type: str, storage_dir: Optional[str] = None) -> ReflectionMemory:
    """
    Get the reflection memory for a specified agent type (global singleton).

    Args:
        agent_type: Agent type
        storage_dir: Storage directory

    Returns:
        Reflection memory instance for the corresponding type
    """
    if agent_type not in _global_memories:
        _global_memories[agent_type] = ReflectionMemory.for_agent(
            agent_type=agent_type,
            storage_dir=storage_dir
        )
        _global_memories[agent_type].load()

    return _global_memories[agent_type]


if __name__ == "__main__":
    # Test code
    memory = ReflectionMemory.for_agent("text")

    # Add test data
    memory.add_reflection(
        task_description="Analyze an ancient martial arts text",
        observation="Extracted 3 scenes, including background, style, and subject information",
        reflection="This analysis covered the main scenes, but detail extraction was not deep enough",
        improvement="Next time, pay more attention to detailed actions and emotional hints in dialogue",
        quality="medium",
        iterations=2
    )

    print("Memory stats:", memory.get_stats())
    print("\nMemory summary:", memory.get_summary())
    print("\nRecent reflections:", memory.get_recent_reflections())
